name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
      uses: docker/login-action@v1.9.0
      with:
        username: ${{ secrets.DOCKER_USER}}
        password: ${{ secrets.DOCKER_PASS}}
    
    - name: Build the Docker image
      working-directory: guestbook
      run: docker build . --tag my-image-name:${DRONE_COMMIT_SHA}
      
    - name: Push Docker image
      run: docker push my-image-name:${DRONE_COMMIT_SHA}
         
         
